// render-worker/src/sfx.js
//
// Built-in sound design, synthesised rather than licensed.
//
// A cut with nothing under it sounds like a slideshow. The usual fix is a
// library of whooshes and impacts, which means licensing, hosting, and a
// picker — a content-acquisition problem wearing an engineering hat.
//
// These are generated by ffmpeg from noise and a sine, which is what most
// transition sounds are underneath. A timeline refers to one as
// `builtin:whoosh`, so the document stays declarative and portable and there is
// no asset to lose. Deterministic too: the same name and duration produce the
// same bytes, which matters because the renderer promises that a timeline
// renders to the same file every time.

'use strict'

const fs = require('fs')
const path = require('path')
const crypto = require('crypto')
const { spawn } = require('child_process')
const { FFMPEG } = require('./sources')

const SCHEME = 'builtin:'
const RATE = 48000

/**
 * A FIXED seed, and bit-exact output.
 *
 * anoisesrc seeds itself from the clock by default, so the same whoosh came out
 * as different bytes on every render. The renderer's whole contract is that one
 * timeline produces one file — "deterministic re-render" is the thing no
 * competitor offers — and a sound that differs every time quietly breaks it.
 * ffmpeg also stamps an encoder string into the wav unless told not to.
 */
const SEED = 20260830

/**
 * Each sound is one lavfi source and one filter chain.
 *
 * The envelopes are written as expressions in `t` rather than as afade steps
 * because a whoosh is not a linear fade — it swells and drops, and the shape is
 * the difference between a transition and a hiss.
 */
const SOUNDS = {
  // Air moving past the camera. Pink noise, band-limited around the middle,
  // swelling to the cut and gone just after it.
  whoosh: (d) => ({
    src: `anoisesrc=color=pink:duration=${d}:sample_rate=${RATE}:amplitude=0.7:seed=${SEED}`,
    chain: [
      'bandpass=frequency=900:width_type=h:width=1400',
      `volume=eval=frame:volume='pow(sin(PI*min(1,t/${d}))\\,1.6)'`,
      'alimiter=limit=0.9',
    ],
  }),
  // The weight under a hard cut: a low sine with a fast exponential decay.
  impact: (d) => ({
    src: `sine=frequency=58:duration=${d}:sample_rate=${RATE}`,
    chain: [
      `volume=eval=frame:volume='exp(-7*t)'`,
      'highpass=f=28',
      'alimiter=limit=0.9',
    ],
  }),
  // Tension before a reveal. Noise that climbs, quadratically so the last third
  // does most of the work.
  riser: (d) => ({
    src: `anoisesrc=color=white:duration=${d}:sample_rate=${RATE}:amplitude=0.5:seed=${SEED + 1}`,
    chain: [
      'highpass=f=600',
      `volume=eval=frame:volume='pow(min(1\\,t/${d})\\,2.2)'`,
      'alimiter=limit=0.85',
    ],
  }),
  // A MUSIC BED, and the reason it is here rather than in a licence.
  //
  // A spot with a voice and nothing under it is austere, which can be a choice,
  // but silence under a voice reads as an unfinished mix far more often than it
  // reads as restraint. What a bed has to do is simple: sit an octave below the
  // voice, never move enough to draw attention, and give the words somewhere to
  // stand.
  //
  // So: a low A, its fifth and its octave, with one slightly detuned partial so
  // the sound breathes instead of sitting dead still, a slow tremolo, and
  // everything above the voice's range rolled off so it never competes.
  bed: (d) => ({
    src: `aevalsrc='0.34*sin(2*PI*55*t)+0.24*sin(2*PI*82.41*t)+0.13*sin(2*PI*110*t)+0.07*sin(2*PI*110.45*t)+0.05*sin(2*PI*164.81*t)':d=${d}:s=${RATE}`,
    chain: [
      'tremolo=f=0.11:d=0.28',
      'lowpass=f=900',
      'highpass=f=38',
      `afade=t=in:st=0:d=1.6`,
      `afade=t=out:st=${Math.max(0, d - 2.2).toFixed(2)}:d=2.2`,
      'alimiter=limit=0.7',
    ],
  }),

  // A soft tick for a caption or a stat appearing.
  click: (d) => ({
    src: `anoisesrc=color=white:duration=${d}:sample_rate=${RATE}:amplitude=0.4:seed=${SEED + 2}`,
    chain: [
      'bandpass=frequency=2600:width_type=h:width=1800',
      `volume=eval=frame:volume='exp(-42*t)'`,
    ],
  }),
}

const DEFAULT_SECONDS = { whoosh: 0.6, impact: 0.5, riser: 1.5, click: 0.12, bed: 30 }
// An accent has no business being six seconds long; a bed has no business being
// six seconds short. The ceiling is per sound rather than one number for all.
const MAX_SECONDS = { whoosh: 6, impact: 6, riser: 8, click: 2, bed: 180 }

function isBuiltin(url) {
  return typeof url === 'string' && url.startsWith(SCHEME)
}

/** `builtin:whoosh` or `builtin:whoosh@0.8` */
function parse(url) {
  const body = String(url).slice(SCHEME.length)
  const [name, secondsRaw] = body.split('@')
  if (!SOUNDS[name]) return null
  const wanted = Number(secondsRaw)
  const seconds = Number.isFinite(wanted) && wanted > 0
    ? Math.min(MAX_SECONDS[name], Math.max(0.05, wanted))
    : DEFAULT_SECONDS[name]
  return { name, seconds }
}

function run(args) {
  return new Promise((resolve, reject) => {
    const p = spawn(FFMPEG, args)
    let err = ''
    p.stderr.on('data', d => { err += d.toString() })
    p.on('error', reject)
    p.on('close', c => (c === 0 ? resolve() : reject(new Error(`ffmpeg ${c}: ${err.slice(-800)}`))))
  })
}

/**
 * Materialises a built-in sound into a wav in `dir` and returns the path.
 * Cached by name and duration, so ten whooshes on one timeline cost one render.
 */
async function materialise(url, dir) {
  const spec = parse(url)
  if (!spec) throw new Error(`Unknown built-in sound: ${url}`)
  const key = crypto.createHash('sha1').update(`${spec.name}:${spec.seconds}`).digest('hex').slice(0, 12)
  const out = path.join(dir, `sfx-${spec.name}-${key}.wav`)
  if (fs.existsSync(out)) return out
  const { src, chain } = SOUNDS[spec.name](spec.seconds)
  await run([
    '-hide_banner', '-loglevel', 'error', '-y',
    '-fflags', '+bitexact', '-flags', '+bitexact',
    '-f', 'lavfi', '-i', src,
    '-af', chain.join(','),
    '-ac', '2', '-ar', String(RATE), '-c:a', 'pcm_s16le',
    out,
  ])
  return out
}

/**
 * Replaces every `builtin:` url in a collected audio item list with a real
 * file. Called before the mix graph is built, so nothing downstream has to know
 * these sounds are synthetic.
 */
async function resolveBuiltins(items, dir) {
  const out = []
  for (const item of items) {
    if (!isBuiltin(item.url)) { out.push(item); continue }
    out.push({ ...item, url: await materialise(item.url, dir) })
  }
  return out
}

module.exports = { SOUNDS, DEFAULT_SECONDS, MAX_SECONDS, isBuiltin, parse, materialise, resolveBuiltins, SCHEME }
