// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zimpimoierpsocnmnizm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppbXBpbW9pZXJwc29jbm1uaXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5Mjk4MjgsImV4cCI6MjA4OTUwNTgyOH0.a82NiYbLkPmyVCxNLQGBeu4I7e4Z0hUy30V21Ur2GRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});